# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('ancho_de_banda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('distribuidor', models.CharField(max_length=20)),
                ('ancho_de_banda', models.IntegerField()),
                ('pago', models.IntegerField(blank=True, null=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedLan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_red', models.GenericIPAddressField()),
                ('ip_host_inicial', models.GenericIPAddressField()),
                ('ip_host_final', models.GenericIPAddressField()),
                ('ip_mascara_de_red', models.GenericIPAddressField()),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Celula')),
                ('servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='celula',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Linea'),
        ),
    ]
