# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redlan',
            name='servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
    ]
