# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0009_auto_20161017_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoInstalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=20)),
                ('monto', models.IntegerField()),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
    ]
