# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagoinstalacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoinstalacion',
            name='concepto',
        ),
    ]
