# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_auto_20161017_1233'),
        ('pagos', '0003_remove_pagoinstalacion_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('año', models.CharField(max_length=4)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
    ]
