# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_auto_20161021_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorenta',
            name='año',
            field=models.IntegerField(max_length=4),
        ),
    ]
