# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_auto_20161021_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorenta',
            name='año',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pagorenta',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')]),
        ),
    ]
