# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_auto_20161021_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorenta',
            name='año',
            field=models.IntegerField(),
        ),
    ]
