# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_auto_20161024_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagorenta',
            name='hora',
        ),
        migrations.AlterField(
            model_name='pagorenta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
