# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_auto_20161025_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorenta',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagorenta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
