# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(blank=True, choices=[('Familiar', 'Familiar'), ('Institucional', 'Institucional')], max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('megas_de_internet', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paquetes')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_de_servicio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Proceso de alta', (('Pendiente instalar la antena', 'Pendiente instalar la antena'),)), ('En servicio', (('Activo', 'Activo'), ('Suspendido', 'Suspendido'))), ('Proceso de Baja', (('Pendiente ir por la antena', 'Pendiente ir por la antena'), ('Baja definitiva', 'Baja definitiva')))], max_length=30)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Paquete')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
