# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='Precio',
            new_name='precio',
        ),
    ]
