# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20160916_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
