# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20161107_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='publico',
        ),
    ]
