# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20160919_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(choices=[('Institucional', (('10 Megas', '10 Megas'), ('20 Megas', '20 Megas'))), ('Familiar', (('Triple Play 5 Megas', 'Triple Play 5 Megas'), ('Triple Play 5 Megas', 'Triple Play 3 Megas')))], max_length=30),
        ),
    ]
