# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_remove_paquete_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
