# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20160919_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Proceso de alta', (('Pendiente instalar la antena', 'Pendiente instalar la antena'),)), ('En servicio', (('Activo', 'Activo'), ('Suspendido', 'Suspendido'))), ('Proceso de Baja', (('Pendiente ir por la antena', 'Pendiente ir por la antena'), ('Baja definitiva', 'Baja definitiva')))], max_length=30),
        ),
    ]
