# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20160919_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes'),
        ),
    ]
