# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_paquete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
