# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_auto_20161004_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Familiar', 'Familiar'), ('Institucional', 'Institucional')], max_length=20, null=True),
        ),
    ]
