# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_paquete_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='paquete',
        ),
        migrations.AddField(
            model_name='servicio',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio.Paquete'),
            preserve_default=False,
        ),
    ]
