# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20160915_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='cliente',
            new_name='perfil',
        ),
    ]
