# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20160915_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido_paterno',
        ),
    ]
